In [ ]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [ ]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [ ]:
x[3]

tensor(3)

In [ ]:
len(x)

4

In [ ]:
x.shape

torch.Size([4])

In [ ]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [ ]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [ ]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [ ]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [ ]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone() #通过分配新内存，讲A的一个副本分配给B
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]), tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵的按元素乘法称为哈达玛积（hadamard product）（数学符号⊙）

In [ ]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [ ]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X,(a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]), torch.Size([2, 3, 4]))

In [ ]:
x = torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [ ]:
A = torch.arange(20*2).reshape(2,5,4)
A.shape,A.sum()

(torch.Size([2, 5, 4]), tensor(780))

In [ ]:
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [ ]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]), torch.Size([5, 4]))

In [ ]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1,A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]), torch.Size([2, 4]))

In [ ]:
A.sum(axis=[0,1]),A.sum(axis=[0,1]).shape

(tensor([180, 190, 200, 210]), torch.Size([4]))

In [ ]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [ ]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [ ]:
#不丢掉被求和维度
sum_A = A.sum(axis=1,keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [ ]:
#因为广播机制要求两个tensor维度个数必须一致，因此keepdims对广播机制很重要
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [ ]:
A.cumsum(axis=0) #某个轴计算A元素的累积总和

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [ ]:
y = torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y) #点积

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [ ]:
torch.sum(x*y)

tensor(6.)

In [ ]:
A.shape,x.shape,torch.mv(A,x),torch.mv(A,x).shape

(torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]),
 torch.Size([5]))

In [ ]:
B = torch.ones(4,3)
torch.mm(A,B),torch.mm(A,B).shape

(tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]), torch.Size([5, 3]))

In [ ]:
#L2范数
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [ ]:
#torch并没有对L1范数进行定义，因此对u取绝对值再累加
torch.abs(u).sum()

tensor(7.)

In [ ]:
#矩阵的F范数
torch.norm(torch.ones((4,9)))

tensor(6.)

In [3]:
import torch

a = torch.ones((2,5,4))
a.shape

torch.Size([2, 5, 4])

In [4]:
a.sum().shape

torch.Size([])

shape为空表示是一个标量

In [5]:
a.sum(axis=1).shape

torch.Size([2, 4])

In [6]:
a.sum(axis=1,keepdims=True).shape

torch.Size([2, 1, 4])

In [7]:
a.sum(axis=[0,2],keepdims=True).shape

torch.Size([1, 5, 1])