假设想对函数y=2xTx 关于列向量x求导

In [ ]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [ ]:
x.requires_grad_(True) #等价于x = torch.arange(4.0,requires_grad=True)
x.grad #默认值是none

In [ ]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

通过调用反向传播函数来自动计算y关于x每个分量的梯度

In [ ]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [ ]:
x.grad == 4*x

tensor([True, True, True, True])

In [ ]:
#默认情况下，pytorch会累积梯度，我们需要清楚之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

在深度学习中，我们的目的不是计算微分矩阵，而是批量中每个样本单独计算的偏导数之和

In [ ]:
#对非标量用backward需要传入一个gradient参数
x.grad.zero_()
y = x * x
#等价于y.backward(torch.ones(len(x))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [ ]:
x.grad.zero_()
y = x * x
u = y.detach() #把y当做一个常数而不是x的函数，即对系统来讲u的值就等于x*x
z = u * x 

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [ ]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

即使构建函数的计算图需要通过python控制流（例如，条件、循环或者任意函数调用），我们仍然可以计算得到变量的梯度

In [ ]:
def f(a):
  b = a * 2
  while b.norm() < 1000:
    b = b * 2
  if b.sum() > 0:
    c = b
  else:
    c = 100 * b
  return c

a = torch.randn(size=(),requires_grad=True) #size是空的话意思是标量
d = f(a)
d.backward()

a.grad == d / a

tensor(True)